name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - run: |
          echo ${ GITHUB_REF }
          haxe -version
          haxelib install hxcpp
          cd ./sample
          haxe build.hxml
