# This is a basic workflow to help you get started with Actions

name: Publish

on:
  release:
    types: [created]

jobs:
  publish-on-haxelib:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - name: Prepare haxelib package
        env:
          PACKAGE_NAME: haxe-poco
        
        run: |
          echo $GITHUB_REF
          mkdir $PACKAGE_NAME

          cp -r src $PACKAGE_NAME
          cp README.md $PACKAGE_NAME
          cp LICENSE $PACKAGE_NAME
          cp haxelib.json $PACKAGE_NAME

      - name: Create GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args:
            - haxe-poco
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}