# This is a basic workflow to help you get started with Actions

name: Publish

on:
  release:
    types: [published]

jobs:
  publish-on-haxelib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - name: Publish
        env:
          PACKAGE_NAME: haxe-poco
        run: |
          echo $GITHUB_REF
          mkdir $PACKAGE_NAME

          cp -r src $PACKAGE_NAME
          cp README.md $PACKAGE_NAME
          cp LICENSE $PACKAGE_NAME
          cp haxelib.json $PACKAGE_NAME

        uses: actions/upload-artifact@v2
        with:
          name: $PACKAGE_NAME
          path: |
            $PACKAGE_NAME
