# This is a basic workflow to help you get started with Actions

name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - name: Publish
        run: |
          echo "TODO: publish to haxelib here"
